// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  deleteApiDropwizardNoteById,
  deleteApiQuarkusNoteById,
  deleteApiSpringNoteById,
  getApiDropwizardCloudMetricsInfo,
  getApiDropwizardHostname,
  getApiDropwizardNote,
  getApiQuarkusCloudMetricsInfo,
  getApiQuarkusHostname,
  getApiQuarkusNote,
  getApiSpringCloudMetricsInfo,
  getApiSpringHostname,
  getApiSpringNote,
  type Options,
  postApiDropwizardNote,
  postApiQuarkusNote,
  postApiSpringNote,
  putApiDropwizardNote,
  putApiQuarkusNote,
  putApiSpringNote,
} from "../sdk.gen"
import type {
  DeleteApiDropwizardNoteByIdData,
  DeleteApiDropwizardNoteByIdError,
  DeleteApiDropwizardNoteByIdResponse,
  DeleteApiQuarkusNoteByIdData,
  DeleteApiQuarkusNoteByIdError,
  DeleteApiQuarkusNoteByIdResponse,
  DeleteApiSpringNoteByIdData,
  DeleteApiSpringNoteByIdError,
  DeleteApiSpringNoteByIdResponse,
  GetApiDropwizardCloudMetricsInfoData,
  GetApiDropwizardCloudMetricsInfoResponse,
  GetApiDropwizardHostnameData,
  GetApiDropwizardHostnameResponse,
  GetApiDropwizardNoteData,
  GetApiDropwizardNoteResponse,
  GetApiQuarkusCloudMetricsInfoData,
  GetApiQuarkusCloudMetricsInfoResponse,
  GetApiQuarkusHostnameData,
  GetApiQuarkusHostnameResponse,
  GetApiQuarkusNoteData,
  GetApiQuarkusNoteResponse,
  GetApiSpringCloudMetricsInfoData,
  GetApiSpringCloudMetricsInfoResponse,
  GetApiSpringHostnameData,
  GetApiSpringHostnameResponse,
  GetApiSpringNoteData,
  GetApiSpringNoteResponse,
  PostApiDropwizardNoteData,
  PostApiDropwizardNoteError,
  PostApiDropwizardNoteResponse,
  PostApiQuarkusNoteData,
  PostApiQuarkusNoteError,
  PostApiQuarkusNoteResponse,
  PostApiSpringNoteData,
  PostApiSpringNoteError,
  PostApiSpringNoteResponse,
  PutApiDropwizardNoteData,
  PutApiDropwizardNoteError,
  PutApiDropwizardNoteResponse,
  PutApiQuarkusNoteData,
  PutApiQuarkusNoteError,
  PutApiQuarkusNoteResponse,
  PutApiSpringNoteData,
  PutApiSpringNoteError,
  PutApiSpringNoteResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiDropwizardCloudMetricsInfoQueryKey = (
  options?: Options<GetApiDropwizardCloudMetricsInfoData>
) => createQueryKey("getApiDropwizardCloudMetricsInfo", options)

/**
 * Cloud static metrics
 *
 * Returns static metrics and image metadata used for framework comparison.
 */
export const getApiDropwizardCloudMetricsInfoOptions = (
  options?: Options<GetApiDropwizardCloudMetricsInfoData>
) =>
  queryOptions<
    GetApiDropwizardCloudMetricsInfoResponse,
    DefaultError,
    GetApiDropwizardCloudMetricsInfoResponse,
    ReturnType<typeof getApiDropwizardCloudMetricsInfoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDropwizardCloudMetricsInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDropwizardCloudMetricsInfoQueryKey(options),
  })

export const getApiDropwizardHostnameQueryKey = (
  options?: Options<GetApiDropwizardHostnameData>
) => createQueryKey("getApiDropwizardHostname", options)

/**
 * Hostname
 *
 * Returns the hostname of the server.
 */
export const getApiDropwizardHostnameOptions = (
  options?: Options<GetApiDropwizardHostnameData>
) =>
  queryOptions<
    GetApiDropwizardHostnameResponse,
    DefaultError,
    GetApiDropwizardHostnameResponse,
    ReturnType<typeof getApiDropwizardHostnameQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDropwizardHostname({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDropwizardHostnameQueryKey(options),
  })

export const getApiDropwizardNoteQueryKey = (
  options?: Options<GetApiDropwizardNoteData>
) => createQueryKey("getApiDropwizardNote", options)

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const getApiDropwizardNoteOptions = (
  options?: Options<GetApiDropwizardNoteData>
) =>
  queryOptions<
    GetApiDropwizardNoteResponse,
    DefaultError,
    GetApiDropwizardNoteResponse,
    ReturnType<typeof getApiDropwizardNoteQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDropwizardNote({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDropwizardNoteQueryKey(options),
  })

/**
 * Create
 *
 * Create a new note.
 */
export const postApiDropwizardNoteMutation = (
  options?: Partial<Options<PostApiDropwizardNoteData>>
): UseMutationOptions<
  PostApiDropwizardNoteResponse,
  PostApiDropwizardNoteError,
  Options<PostApiDropwizardNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiDropwizardNoteResponse,
    PostApiDropwizardNoteError,
    Options<PostApiDropwizardNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiDropwizardNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update
 *
 * Update an existing note.
 */
export const putApiDropwizardNoteMutation = (
  options?: Partial<Options<PutApiDropwizardNoteData>>
): UseMutationOptions<
  PutApiDropwizardNoteResponse,
  PutApiDropwizardNoteError,
  Options<PutApiDropwizardNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiDropwizardNoteResponse,
    PutApiDropwizardNoteError,
    Options<PutApiDropwizardNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiDropwizardNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 *
 * Delete an existing note.
 */
export const deleteApiDropwizardNoteByIdMutation = (
  options?: Partial<Options<DeleteApiDropwizardNoteByIdData>>
): UseMutationOptions<
  DeleteApiDropwizardNoteByIdResponse,
  DeleteApiDropwizardNoteByIdError,
  Options<DeleteApiDropwizardNoteByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiDropwizardNoteByIdResponse,
    DeleteApiDropwizardNoteByIdError,
    Options<DeleteApiDropwizardNoteByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiDropwizardNoteById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiQuarkusCloudMetricsInfoQueryKey = (
  options?: Options<GetApiQuarkusCloudMetricsInfoData>
) => createQueryKey("getApiQuarkusCloudMetricsInfo", options)

/**
 * Cloud static metrics
 *
 * Returns static metrics and image metadata used for framework comparison.
 */
export const getApiQuarkusCloudMetricsInfoOptions = (
  options?: Options<GetApiQuarkusCloudMetricsInfoData>
) =>
  queryOptions<
    GetApiQuarkusCloudMetricsInfoResponse,
    DefaultError,
    GetApiQuarkusCloudMetricsInfoResponse,
    ReturnType<typeof getApiQuarkusCloudMetricsInfoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiQuarkusCloudMetricsInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiQuarkusCloudMetricsInfoQueryKey(options),
  })

export const getApiQuarkusHostnameQueryKey = (
  options?: Options<GetApiQuarkusHostnameData>
) => createQueryKey("getApiQuarkusHostname", options)

/**
 * Hostname
 *
 * Returns the hostname of the server.
 */
export const getApiQuarkusHostnameOptions = (
  options?: Options<GetApiQuarkusHostnameData>
) =>
  queryOptions<
    GetApiQuarkusHostnameResponse,
    DefaultError,
    GetApiQuarkusHostnameResponse,
    ReturnType<typeof getApiQuarkusHostnameQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiQuarkusHostname({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiQuarkusHostnameQueryKey(options),
  })

export const getApiQuarkusNoteQueryKey = (
  options?: Options<GetApiQuarkusNoteData>
) => createQueryKey("getApiQuarkusNote", options)

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const getApiQuarkusNoteOptions = (
  options?: Options<GetApiQuarkusNoteData>
) =>
  queryOptions<
    GetApiQuarkusNoteResponse,
    DefaultError,
    GetApiQuarkusNoteResponse,
    ReturnType<typeof getApiQuarkusNoteQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiQuarkusNote({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiQuarkusNoteQueryKey(options),
  })

/**
 * Create
 *
 * Create a new note.
 */
export const postApiQuarkusNoteMutation = (
  options?: Partial<Options<PostApiQuarkusNoteData>>
): UseMutationOptions<
  PostApiQuarkusNoteResponse,
  PostApiQuarkusNoteError,
  Options<PostApiQuarkusNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiQuarkusNoteResponse,
    PostApiQuarkusNoteError,
    Options<PostApiQuarkusNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiQuarkusNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update
 *
 * Update an existing note.
 */
export const putApiQuarkusNoteMutation = (
  options?: Partial<Options<PutApiQuarkusNoteData>>
): UseMutationOptions<
  PutApiQuarkusNoteResponse,
  PutApiQuarkusNoteError,
  Options<PutApiQuarkusNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiQuarkusNoteResponse,
    PutApiQuarkusNoteError,
    Options<PutApiQuarkusNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiQuarkusNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 *
 * Delete an existing note.
 */
export const deleteApiQuarkusNoteByIdMutation = (
  options?: Partial<Options<DeleteApiQuarkusNoteByIdData>>
): UseMutationOptions<
  DeleteApiQuarkusNoteByIdResponse,
  DeleteApiQuarkusNoteByIdError,
  Options<DeleteApiQuarkusNoteByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiQuarkusNoteByIdResponse,
    DeleteApiQuarkusNoteByIdError,
    Options<DeleteApiQuarkusNoteByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiQuarkusNoteById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpringNoteQueryKey = (
  options?: Options<GetApiSpringNoteData>
) => createQueryKey("getApiSpringNote", options)

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const getApiSpringNoteOptions = (
  options?: Options<GetApiSpringNoteData>
) =>
  queryOptions<
    GetApiSpringNoteResponse,
    DefaultError,
    GetApiSpringNoteResponse,
    ReturnType<typeof getApiSpringNoteQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpringNote({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpringNoteQueryKey(options),
  })

/**
 * Create
 *
 * Create a new note.
 */
export const postApiSpringNoteMutation = (
  options?: Partial<Options<PostApiSpringNoteData>>
): UseMutationOptions<
  PostApiSpringNoteResponse,
  PostApiSpringNoteError,
  Options<PostApiSpringNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiSpringNoteResponse,
    PostApiSpringNoteError,
    Options<PostApiSpringNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiSpringNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update
 *
 * Update an existing note.
 */
export const putApiSpringNoteMutation = (
  options?: Partial<Options<PutApiSpringNoteData>>
): UseMutationOptions<
  PutApiSpringNoteResponse,
  PutApiSpringNoteError,
  Options<PutApiSpringNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiSpringNoteResponse,
    PutApiSpringNoteError,
    Options<PutApiSpringNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiSpringNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpringHostnameQueryKey = (
  options?: Options<GetApiSpringHostnameData>
) => createQueryKey("getApiSpringHostname", options)

/**
 * Hostname
 *
 * Returns the hostname of the server.
 */
export const getApiSpringHostnameOptions = (
  options?: Options<GetApiSpringHostnameData>
) =>
  queryOptions<
    GetApiSpringHostnameResponse,
    DefaultError,
    GetApiSpringHostnameResponse,
    ReturnType<typeof getApiSpringHostnameQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpringHostname({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpringHostnameQueryKey(options),
  })

export const getApiSpringCloudMetricsInfoQueryKey = (
  options?: Options<GetApiSpringCloudMetricsInfoData>
) => createQueryKey("getApiSpringCloudMetricsInfo", options)

/**
 * Cloud static metrics
 *
 * Returns static metrics and image metadata used for framework comparison.
 */
export const getApiSpringCloudMetricsInfoOptions = (
  options?: Options<GetApiSpringCloudMetricsInfoData>
) =>
  queryOptions<
    GetApiSpringCloudMetricsInfoResponse,
    DefaultError,
    GetApiSpringCloudMetricsInfoResponse,
    ReturnType<typeof getApiSpringCloudMetricsInfoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpringCloudMetricsInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpringCloudMetricsInfoQueryKey(options),
  })

/**
 * Delete
 *
 * Delete an existing note.
 */
export const deleteApiSpringNoteByIdMutation = (
  options?: Partial<Options<DeleteApiSpringNoteByIdData>>
): UseMutationOptions<
  DeleteApiSpringNoteByIdResponse,
  DeleteApiSpringNoteByIdError,
  Options<DeleteApiSpringNoteByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiSpringNoteByIdResponse,
    DeleteApiSpringNoteByIdError,
    Options<DeleteApiSpringNoteByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiSpringNoteById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
