// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  deleteApiDropwizardNoteById,
  deleteApiQuarkusNoteById,
  getApiDropwizardHostname,
  getApiDropwizardNote,
  getApiQuarkusHostname,
  getApiQuarkusNote,
  openapiCreate,
  openapiDelete,
  openapiGetAll,
  openapiHostname,
  openapiUpdate,
  type Options,
  postApiDropwizardNote,
  postApiQuarkusNote,
  putApiDropwizardNote,
  putApiQuarkusNote,
} from "../sdk.gen"
import type {
  DeleteApiDropwizardNoteByIdData,
  DeleteApiDropwizardNoteByIdError,
  DeleteApiDropwizardNoteByIdResponse,
  DeleteApiQuarkusNoteByIdData,
  DeleteApiQuarkusNoteByIdError,
  DeleteApiQuarkusNoteByIdResponse,
  GetApiDropwizardHostnameData,
  GetApiDropwizardHostnameResponse,
  GetApiDropwizardNoteData,
  GetApiDropwizardNoteResponse,
  GetApiQuarkusHostnameData,
  GetApiQuarkusHostnameResponse,
  GetApiQuarkusNoteData,
  GetApiQuarkusNoteResponse,
  OpenapiCreateData,
  OpenapiCreateError,
  OpenapiCreateResponse,
  OpenapiDeleteData,
  OpenapiDeleteError,
  OpenapiDeleteResponse,
  OpenapiGetAllData,
  OpenapiGetAllResponse,
  OpenapiHostnameData,
  OpenapiHostnameResponse,
  OpenapiUpdateData,
  OpenapiUpdateError,
  OpenapiUpdateResponse,
  PostApiDropwizardNoteData,
  PostApiDropwizardNoteError,
  PostApiDropwizardNoteResponse,
  PostApiQuarkusNoteData,
  PostApiQuarkusNoteError,
  PostApiQuarkusNoteResponse,
  PutApiDropwizardNoteData,
  PutApiDropwizardNoteError,
  PutApiDropwizardNoteResponse,
  PutApiQuarkusNoteData,
  PutApiQuarkusNoteError,
  PutApiQuarkusNoteResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiDropwizardHostnameQueryKey = (
  options?: Options<GetApiDropwizardHostnameData>
) => createQueryKey("getApiDropwizardHostname", options)

/**
 * Hostname
 *
 * Returns the hostname of the server.
 */
export const getApiDropwizardHostnameOptions = (
  options?: Options<GetApiDropwizardHostnameData>
) =>
  queryOptions<
    GetApiDropwizardHostnameResponse,
    DefaultError,
    GetApiDropwizardHostnameResponse,
    ReturnType<typeof getApiDropwizardHostnameQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDropwizardHostname({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDropwizardHostnameQueryKey(options),
  })

export const getApiDropwizardNoteQueryKey = (
  options?: Options<GetApiDropwizardNoteData>
) => createQueryKey("getApiDropwizardNote", options)

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const getApiDropwizardNoteOptions = (
  options?: Options<GetApiDropwizardNoteData>
) =>
  queryOptions<
    GetApiDropwizardNoteResponse,
    DefaultError,
    GetApiDropwizardNoteResponse,
    ReturnType<typeof getApiDropwizardNoteQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiDropwizardNote({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiDropwizardNoteQueryKey(options),
  })

/**
 * Create
 *
 * Create a new note.
 */
export const postApiDropwizardNoteMutation = (
  options?: Partial<Options<PostApiDropwizardNoteData>>
): UseMutationOptions<
  PostApiDropwizardNoteResponse,
  PostApiDropwizardNoteError,
  Options<PostApiDropwizardNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiDropwizardNoteResponse,
    PostApiDropwizardNoteError,
    Options<PostApiDropwizardNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiDropwizardNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update
 *
 * Update an existing note.
 */
export const putApiDropwizardNoteMutation = (
  options?: Partial<Options<PutApiDropwizardNoteData>>
): UseMutationOptions<
  PutApiDropwizardNoteResponse,
  PutApiDropwizardNoteError,
  Options<PutApiDropwizardNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiDropwizardNoteResponse,
    PutApiDropwizardNoteError,
    Options<PutApiDropwizardNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiDropwizardNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 *
 * Delete an existing note.
 */
export const deleteApiDropwizardNoteByIdMutation = (
  options?: Partial<Options<DeleteApiDropwizardNoteByIdData>>
): UseMutationOptions<
  DeleteApiDropwizardNoteByIdResponse,
  DeleteApiDropwizardNoteByIdError,
  Options<DeleteApiDropwizardNoteByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiDropwizardNoteByIdResponse,
    DeleteApiDropwizardNoteByIdError,
    Options<DeleteApiDropwizardNoteByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiDropwizardNoteById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiQuarkusHostnameQueryKey = (
  options?: Options<GetApiQuarkusHostnameData>
) => createQueryKey("getApiQuarkusHostname", options)

/**
 * Hostname
 */
export const getApiQuarkusHostnameOptions = (
  options?: Options<GetApiQuarkusHostnameData>
) =>
  queryOptions<
    GetApiQuarkusHostnameResponse,
    DefaultError,
    GetApiQuarkusHostnameResponse,
    ReturnType<typeof getApiQuarkusHostnameQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiQuarkusHostname({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiQuarkusHostnameQueryKey(options),
  })

export const getApiQuarkusNoteQueryKey = (
  options?: Options<GetApiQuarkusNoteData>
) => createQueryKey("getApiQuarkusNote", options)

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const getApiQuarkusNoteOptions = (
  options?: Options<GetApiQuarkusNoteData>
) =>
  queryOptions<
    GetApiQuarkusNoteResponse,
    DefaultError,
    GetApiQuarkusNoteResponse,
    ReturnType<typeof getApiQuarkusNoteQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiQuarkusNote({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiQuarkusNoteQueryKey(options),
  })

/**
 * Create
 *
 * Create a new note.
 */
export const postApiQuarkusNoteMutation = (
  options?: Partial<Options<PostApiQuarkusNoteData>>
): UseMutationOptions<
  PostApiQuarkusNoteResponse,
  PostApiQuarkusNoteError,
  Options<PostApiQuarkusNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiQuarkusNoteResponse,
    PostApiQuarkusNoteError,
    Options<PostApiQuarkusNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiQuarkusNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update
 *
 * Update an existing note.
 */
export const putApiQuarkusNoteMutation = (
  options?: Partial<Options<PutApiQuarkusNoteData>>
): UseMutationOptions<
  PutApiQuarkusNoteResponse,
  PutApiQuarkusNoteError,
  Options<PutApiQuarkusNoteData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiQuarkusNoteResponse,
    PutApiQuarkusNoteError,
    Options<PutApiQuarkusNoteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiQuarkusNote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 *
 * Delete an existing note.
 */
export const deleteApiQuarkusNoteByIdMutation = (
  options?: Partial<Options<DeleteApiQuarkusNoteByIdData>>
): UseMutationOptions<
  DeleteApiQuarkusNoteByIdResponse,
  DeleteApiQuarkusNoteByIdError,
  Options<DeleteApiQuarkusNoteByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiQuarkusNoteByIdResponse,
    DeleteApiQuarkusNoteByIdError,
    Options<DeleteApiQuarkusNoteByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiQuarkusNoteById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiGetAllQueryKey = (options?: Options<OpenapiGetAllData>) =>
  createQueryKey("openapiGetAll", options)

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const openapiGetAllOptions = (options?: Options<OpenapiGetAllData>) =>
  queryOptions<
    OpenapiGetAllResponse,
    DefaultError,
    OpenapiGetAllResponse,
    ReturnType<typeof openapiGetAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiGetAllQueryKey(options),
  })

/**
 * Create
 *
 * Create a new note.
 */
export const openapiCreateMutation = (
  options?: Partial<Options<OpenapiCreateData>>
): UseMutationOptions<
  OpenapiCreateResponse,
  OpenapiCreateError,
  Options<OpenapiCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiCreateResponse,
    OpenapiCreateError,
    Options<OpenapiCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update
 *
 * Update an existing note.
 */
export const openapiUpdateMutation = (
  options?: Partial<Options<OpenapiUpdateData>>
): UseMutationOptions<
  OpenapiUpdateResponse,
  OpenapiUpdateError,
  Options<OpenapiUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiUpdateResponse,
    OpenapiUpdateError,
    Options<OpenapiUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiHostnameQueryKey = (
  options?: Options<OpenapiHostnameData>
) => createQueryKey("openapiHostname", options)

/**
 * Hostname
 *
 * Returns the hostname of the server.
 */
export const openapiHostnameOptions = (
  options?: Options<OpenapiHostnameData>
) =>
  queryOptions<
    OpenapiHostnameResponse,
    DefaultError,
    OpenapiHostnameResponse,
    ReturnType<typeof openapiHostnameQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiHostname({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiHostnameQueryKey(options),
  })

/**
 * Delete
 *
 * Delete an existing note.
 */
export const openapiDeleteMutation = (
  options?: Partial<Options<OpenapiDeleteData>>
): UseMutationOptions<
  OpenapiDeleteResponse,
  OpenapiDeleteError,
  Options<OpenapiDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiDeleteResponse,
    OpenapiDeleteError,
    Options<OpenapiDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
