mp.openapi.scan.packages=dev.martindotpy.dropwizardquarkusspring.dropwizard,dev.martindotpy.dropwizardquarkusspring.shared,io.dropwizard.jersey
mp.openapi.extensions.smallrye.info.title=Dropwizard API
mp.openapi.extensions.smallrye.info.version=1.0.0-SNAPSHOT
mp.openapi.filter=dev.martindotpy.dropwizardquarkusspring.dropwizard.core.adapter.openapi.ErrorsRequiredFieldsFilter
