# App
quarkus.application.name=Quarkus
quarkus.http.port=8081
quarkus.http.test-port=0
quarkus.compose.devservices.files=../docker-compose-devservices.yaml
quarkus.compose.devservices.project-name=dropwizard-quarkus-spring
# Dev
%dev.quarkus.live-reload.instrumentation=true
%dev.quarkus.compose.devservices.profiles=dev
%dev.quarkus.mongodb.connection-string=mongodb://admin:admin@localhost:27017/notes-db?authSource=admin
# Test
%test.quarkus.compose.devservices.profiles=test
%test.quarkus.mongodb.credentials.username=admin
%test.quarkus.mongodb.credentials.password=admin
%test.quarkus.mongodb.credentials.auth-source=admin
# Prod
%prod.quarkus.mongodb.credentials.username=${MONGO_USERNAME}
%prod.quarkus.mongodb.credentials.password=${MONGO_PASSWORD}
%prod.quarkus.mongodb.credentials.auth-source=${MONGO_AUTH_SOURCE}
# MongoDb
quarkus.mongodb.database=notes-db
# Openapi
quarkus.smallrye-openapi.path=/api/quarkus/openapi.json
mp.openapi.filter=dev.martindotpy.dropwizardquarkusspring.quarkus.core.adapter.openapi.ProblemDetailsRequiredFieldsFilter
# HTTP Client
quarkus.rest-client.ghcr-token-api.url=https://ghcr.io
quarkus.rest-client.ghcr-token-api.scope=jakarta.inject.Singleton
quarkus.rest-client.ghcr-manifest-api.url=https://ghcr.io
quarkus.rest-client.ghcr-manifest-api.scope=jakarta.inject.Singleton
# Validation
quarkus.resteasy.problem.constraint-violation.status=422
quarkus.resteasy.problem.constraint-violation.title=Constraint violation
# Performance
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
