---
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9091
  gzip:
    syncFlush: true

logging:
  level: INFO
  loggers:
    dev.martindotpy: DEBUG

mongo:
  uri: ${MONGO_URI:-mongodb://admin:admin@localhost:27017/notes-db?authSource=admin}
  database: notes-db
