# App
spring.application.name=Spring API
spring.application.version=@project.version@
server.port=8082
spring.mvc.problemdetails.enabled=true
spring.config.import=optional:file:.env[.properties]
spring.devtools.livereload.enabled=true
# Dev
spring.docker.compose.file=../docker-compose-devservices.yaml
spring.docker.compose.profiles.active=dev
# MongoDb
spring.mongodb.database=notes-db
# Openapi
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/api/spring/openapi.json
springdoc.open-api.info.title=${spring.application.name}
springdoc.open-api.info.version=${spring.application.version}
