// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  DeleteApiDropwizardNoteByIdData,
  DeleteApiDropwizardNoteByIdErrors,
  DeleteApiDropwizardNoteByIdResponses,
  DeleteApiQuarkusNoteByIdData,
  DeleteApiQuarkusNoteByIdErrors,
  DeleteApiQuarkusNoteByIdResponses,
  GetApiDropwizardCloudMetricsInfoData,
  GetApiDropwizardCloudMetricsInfoResponses,
  GetApiDropwizardCloudMetricsLiveData,
  GetApiDropwizardCloudMetricsLiveResponse,
  GetApiDropwizardCloudMetricsLiveResponses,
  GetApiDropwizardHostnameData,
  GetApiDropwizardHostnameResponses,
  GetApiDropwizardNoteData,
  GetApiDropwizardNoteResponses,
  GetApiQuarkusCloudMetricsInfoData,
  GetApiQuarkusCloudMetricsInfoResponses,
  GetApiQuarkusCloudMetricsLiveData,
  GetApiQuarkusCloudMetricsLiveResponse,
  GetApiQuarkusCloudMetricsLiveResponses,
  GetApiQuarkusHostnameData,
  GetApiQuarkusHostnameResponses,
  GetApiQuarkusNoteData,
  GetApiQuarkusNoteResponses,
  OpenapiCreateData,
  OpenapiCreateErrors,
  OpenapiCreateResponses,
  OpenapiDeleteData,
  OpenapiDeleteErrors,
  OpenapiDeleteResponses,
  OpenapiGetAllData,
  OpenapiGetAllResponses,
  OpenapiHostnameData,
  OpenapiHostnameResponses,
  OpenapiLiveMetricsStreamData,
  OpenapiLiveMetricsStreamResponse,
  OpenapiLiveMetricsStreamResponses,
  OpenapiStaticMetricsData,
  OpenapiStaticMetricsResponses,
  OpenapiUpdateData,
  OpenapiUpdateErrors,
  OpenapiUpdateResponses,
  PostApiDropwizardNoteData,
  PostApiDropwizardNoteErrors,
  PostApiDropwizardNoteResponses,
  PostApiQuarkusNoteData,
  PostApiQuarkusNoteErrors,
  PostApiQuarkusNoteResponses,
  PutApiDropwizardNoteData,
  PutApiDropwizardNoteErrors,
  PutApiDropwizardNoteResponses,
  PutApiQuarkusNoteData,
  PutApiQuarkusNoteErrors,
  PutApiQuarkusNoteResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Cloud static metrics
 *
 * Returns static metrics and image metadata used for framework comparison.
 */
export const getApiDropwizardCloudMetricsInfo = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiDropwizardCloudMetricsInfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiDropwizardCloudMetricsInfoResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/dropwizard/cloud/metrics/info", ...options })

/**
 * Cloud live metrics stream
 *
 * Streams live startup and runtime metrics as server-sent events.
 */
export const getApiDropwizardCloudMetricsLive = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetApiDropwizardCloudMetricsLiveData,
    ThrowOnError,
    GetApiDropwizardCloudMetricsLiveResponse
  >
) =>
  (options?.client ?? client).sse.get<
    GetApiDropwizardCloudMetricsLiveResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/dropwizard/cloud/metrics/live", ...options })

/**
 * Hostname
 *
 * Returns the hostname of the server.
 */
export const getApiDropwizardHostname = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDropwizardHostnameData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiDropwizardHostnameResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/dropwizard/hostname", ...options })

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const getApiDropwizardNote = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDropwizardNoteData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiDropwizardNoteResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/dropwizard/note", ...options })

/**
 * Create
 *
 * Create a new note.
 */
export const postApiDropwizardNote = <ThrowOnError extends boolean = false>(
  options: Options<PostApiDropwizardNoteData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiDropwizardNoteResponses,
    PostApiDropwizardNoteErrors,
    ThrowOnError
  >({
    url: "/api/dropwizard/note",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update
 *
 * Update an existing note.
 */
export const putApiDropwizardNote = <ThrowOnError extends boolean = false>(
  options: Options<PutApiDropwizardNoteData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiDropwizardNoteResponses,
    PutApiDropwizardNoteErrors,
    ThrowOnError
  >({
    url: "/api/dropwizard/note",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete
 *
 * Delete an existing note.
 */
export const deleteApiDropwizardNoteById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiDropwizardNoteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiDropwizardNoteByIdResponses,
    DeleteApiDropwizardNoteByIdErrors,
    ThrowOnError
  >({ url: "/api/dropwizard/note/{id}", ...options })

/**
 * Cloud static metrics
 *
 * Returns static metrics and image metadata used for framework comparison.
 */
export const getApiQuarkusCloudMetricsInfo = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiQuarkusCloudMetricsInfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiQuarkusCloudMetricsInfoResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/quarkus/cloud/metrics/info", ...options })

/**
 * Cloud live metrics stream
 *
 * Streams live startup and runtime metrics as server-sent events.
 */
export const getApiQuarkusCloudMetricsLive = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetApiQuarkusCloudMetricsLiveData,
    ThrowOnError,
    GetApiQuarkusCloudMetricsLiveResponse
  >
) =>
  (options?.client ?? client).sse.get<
    GetApiQuarkusCloudMetricsLiveResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/quarkus/cloud/metrics/live", ...options })

/**
 * Hostname
 */
export const getApiQuarkusHostname = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiQuarkusHostnameData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiQuarkusHostnameResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/quarkus/hostname", ...options })

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const getApiQuarkusNote = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiQuarkusNoteData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiQuarkusNoteResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/quarkus/note", ...options })

/**
 * Create
 *
 * Create a new note.
 */
export const postApiQuarkusNote = <ThrowOnError extends boolean = false>(
  options: Options<PostApiQuarkusNoteData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiQuarkusNoteResponses,
    PostApiQuarkusNoteErrors,
    ThrowOnError
  >({
    url: "/api/quarkus/note",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update
 *
 * Update an existing note.
 */
export const putApiQuarkusNote = <ThrowOnError extends boolean = false>(
  options: Options<PutApiQuarkusNoteData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutApiQuarkusNoteResponses,
    PutApiQuarkusNoteErrors,
    ThrowOnError
  >({
    url: "/api/quarkus/note",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete
 *
 * Delete an existing note.
 */
export const deleteApiQuarkusNoteById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiQuarkusNoteByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiQuarkusNoteByIdResponses,
    DeleteApiQuarkusNoteByIdErrors,
    ThrowOnError
  >({ url: "/api/quarkus/note/{id}", ...options })

/**
 * Get all
 *
 * Retrieve all notes.
 */
export const openapiGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiGetAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    OpenapiGetAllResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/spring/note", ...options })

/**
 * Create
 *
 * Create a new note.
 */
export const openapiCreate = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    OpenapiCreateResponses,
    OpenapiCreateErrors,
    ThrowOnError
  >({
    url: "/api/spring/note",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update
 *
 * Update an existing note.
 */
export const openapiUpdate = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiUpdateData, ThrowOnError>
) =>
  (options.client ?? client).put<
    OpenapiUpdateResponses,
    OpenapiUpdateErrors,
    ThrowOnError
  >({
    url: "/api/spring/note",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Hostname
 *
 * Returns the hostname of the server.
 */
export const openapiHostname = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiHostnameData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    OpenapiHostnameResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/spring/hostname", ...options })

/**
 * Cloud live metrics stream
 *
 * Streams live startup and runtime metrics as server-sent events.
 */
export const openapiLiveMetricsStream = <ThrowOnError extends boolean = false>(
  options?: Options<
    OpenapiLiveMetricsStreamData,
    ThrowOnError,
    OpenapiLiveMetricsStreamResponse
  >
) =>
  (options?.client ?? client).sse.get<
    OpenapiLiveMetricsStreamResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/spring/cloud/metrics/live", ...options })

/**
 * Cloud static metrics
 *
 * Returns static metrics and image metadata used for framework comparison.
 */
export const openapiStaticMetrics = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiStaticMetricsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    OpenapiStaticMetricsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/spring/cloud/metrics/info", ...options })

/**
 * Delete
 *
 * Delete an existing note.
 */
export const openapiDelete = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    OpenapiDeleteResponses,
    OpenapiDeleteErrors,
    ThrowOnError
  >({ url: "/api/spring/note/{id}", ...options })
