// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8082" | (string & {})
}

export type OpenapiErrorMessage = {
  code: number
  message: string
  details?: string
}

export type OpenapiErrorMessagePublic = {
  code: number
  message: string
  details?: string
}

export type OpenapiImageManifestSummary = {
  image?: string
  imageReference?: string
  platforms?: Array<OpenapiImagePlatformDigest>
}

export type OpenapiImagePlatformDigest = {
  architecture?: string
  digest?: string
  size?: number
}

export type OpenapiNotNullDataResponseListNotePublic = {
  data: Array<OpenapiNotePublic>
  detail: string
}

export type OpenapiNotNullDataResponseNotePublic = {
  data: OpenapiNotePublic
  detail: string
}

export type OpenapiNoteCreate = {
  content: string
}

export type OpenapiNotePublic = {
  id: string
  content: string
}

export type OpenapiNoteUpdate = {
  id: string
  content: string
}

export type OpenapiServiceComparasion = {
  framework?: string
  service?: string
  runtimeMode?: string
  version?: string
  hostname?: string
  startupReadyMs?: number
  images?: Array<OpenapiImageManifestSummary>
}

export type OpenapiServiceLiveMetrics = {
  collectedAt?: string
  startupMetrics?: OpenapiServiceStartupMetrics
  resourceSnapshot?: OpenapiServiceResourceSnapshot
}

export type OpenapiServiceResourceSnapshot = {
  availableProcessors?: number
  maxMemoryBytes?: number
  totalMemoryBytes?: number
  freeMemoryBytes?: number
  usedMemoryBytes?: number
  usedMemoryMiB?: number
  javaVersion?: string
  vmName?: string
  osName?: string
  osArch?: string
}

export type OpenapiServiceStartupMetrics = {
  processStartedAt?: string
  processUptimeMs?: number
  processUptimeSeconds?: number
}

export type OpenapiSimpleResponse = {
  detail: string
}

export type OpenapiValidationErrorMessage = {
  errors: Array<string>
}

export type OpenapiValidationErrorMessagePublic = {
  errors: Array<string>
}

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export type OpenapiHttpProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance: string
  [key: string]: unknown
}

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export type OpenapiHttpValidationProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance: string
  /**
   * List of validation constraint violations that occurred
   */
  violations?: Array<OpenapiViolation>
  [key: string]: unknown
}

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export type OpenapiHttpValidationProblemPublic = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status?: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance?: string
  /**
   * List of validation constraint violations that occurred
   */
  violations?: Array<OpenapiViolationPublic>
  [key: string]: unknown
}

export type OpenapiMediaType = {
  type?: string
  subtype?: string
  parameters?: {
    [key: string]: string
  }
  hash?: number
  wildcardType?: boolean
  wildcardSubtype?: boolean
}

export type OpenapiOutboundSseEvent = {
  id?: string
  name?: string
  comment?: string
  reconnectDelay?: number
  reconnectDelaySet?: boolean
  type?: {
    [key: string]: unknown
  }
  genericType?: {
    [key: string]: unknown
  }
  mediaType?: OpenapiMediaType
  data?: unknown
}

/**
 * Validation constraint violation details
 */
export type OpenapiViolation = {
  /**
   * The field for which the validation failed
   */
  field: string
  /**
   * Part of the http request where the validation error occurred such as query, path, header, form, body
   */
  in: string
  /**
   * Description of the validation error
   */
  message: string
}

/**
 * Validation constraint violation details
 */
export type OpenapiViolationPublic = {
  /**
   * The field for which the validation failed
   */
  field?: string
  /**
   * Part of the http request where the validation error occurred such as query, path, header, form, body
   */
  in?: string
  /**
   * Description of the validation error
   */
  message?: string
}

export type OpenapiProblemDetailPublic = {
  type?: string
  title?: string
  status?: number
  detail?: string
  instance?: string
  properties?: {
    [key: string]: unknown
  }
}

export type OpenapiSseEmitter = {
  timeout?: number
}

export type OpenapiProblemDetail = {
  type?: string
  title?: string
  status?: number
  detail?: string
  instance?: string
  properties?: {
    [key: string]: unknown
  }
}

export type GetApiDropwizardCloudMetricsInfoData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dropwizard/cloud/metrics/info"
}

export type GetApiDropwizardCloudMetricsInfoResponses = {
  /**
   * Cloud static metrics retrieved successfully
   */
  200: OpenapiServiceComparasion
}

export type GetApiDropwizardCloudMetricsInfoResponse =
  GetApiDropwizardCloudMetricsInfoResponses[keyof GetApiDropwizardCloudMetricsInfoResponses]

export type GetApiDropwizardCloudMetricsLiveData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dropwizard/cloud/metrics/live"
}

export type GetApiDropwizardCloudMetricsLiveResponses = {
  /**
   * Cloud live metrics stream started
   */
  200: OpenapiServiceLiveMetrics
}

export type GetApiDropwizardCloudMetricsLiveResponse =
  GetApiDropwizardCloudMetricsLiveResponses[keyof GetApiDropwizardCloudMetricsLiveResponses]

export type GetApiDropwizardHostnameData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dropwizard/hostname"
}

export type GetApiDropwizardHostnameResponses = {
  /**
   * OK
   */
  200: string
}

export type GetApiDropwizardHostnameResponse =
  GetApiDropwizardHostnameResponses[keyof GetApiDropwizardHostnameResponses]

export type GetApiDropwizardNoteData = {
  body?: never
  path?: never
  query?: never
  url: "/api/dropwizard/note"
}

export type GetApiDropwizardNoteResponses = {
  /**
   * Notes retrieved successfully
   */
  200: OpenapiNotNullDataResponseListNotePublic
}

export type GetApiDropwizardNoteResponse =
  GetApiDropwizardNoteResponses[keyof GetApiDropwizardNoteResponses]

export type PostApiDropwizardNoteData = {
  body: OpenapiNoteCreate
  path?: never
  query?: never
  url: "/api/dropwizard/note"
}

export type PostApiDropwizardNoteErrors = {
  /**
   * Validation error
   */
  422: OpenapiValidationErrorMessagePublic
}

export type PostApiDropwizardNoteError =
  PostApiDropwizardNoteErrors[keyof PostApiDropwizardNoteErrors]

export type PostApiDropwizardNoteResponses = {
  /**
   * Note created successfully
   */
  200: OpenapiNotNullDataResponseNotePublic
}

export type PostApiDropwizardNoteResponse =
  PostApiDropwizardNoteResponses[keyof PostApiDropwizardNoteResponses]

export type PutApiDropwizardNoteData = {
  body: OpenapiNoteUpdate
  path?: never
  query?: never
  url: "/api/dropwizard/note"
}

export type PutApiDropwizardNoteErrors = {
  /**
   * Note not found
   */
  404: OpenapiErrorMessagePublic
  /**
   * Validation error
   */
  422: OpenapiValidationErrorMessagePublic
}

export type PutApiDropwizardNoteError =
  PutApiDropwizardNoteErrors[keyof PutApiDropwizardNoteErrors]

export type PutApiDropwizardNoteResponses = {
  /**
   * Note updated successfully
   */
  200: OpenapiNotNullDataResponseNotePublic
}

export type PutApiDropwizardNoteResponse =
  PutApiDropwizardNoteResponses[keyof PutApiDropwizardNoteResponses]

export type DeleteApiDropwizardNoteByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/dropwizard/note/{id}"
}

export type DeleteApiDropwizardNoteByIdErrors = {
  /**
   * Note not found
   */
  404: OpenapiErrorMessage
  /**
   * Validation error
   */
  422: OpenapiValidationErrorMessage
  /**
   * Internal Server Error
   */
  500: OpenapiErrorMessage
}

export type DeleteApiDropwizardNoteByIdError =
  DeleteApiDropwizardNoteByIdErrors[keyof DeleteApiDropwizardNoteByIdErrors]

export type DeleteApiDropwizardNoteByIdResponses = {
  /**
   * Note deleted successfully
   */
  200: OpenapiSimpleResponse
}

export type DeleteApiDropwizardNoteByIdResponse =
  DeleteApiDropwizardNoteByIdResponses[keyof DeleteApiDropwizardNoteByIdResponses]

export type GetApiQuarkusCloudMetricsInfoData = {
  body?: never
  path?: never
  query?: never
  url: "/api/quarkus/cloud/metrics/info"
}

export type GetApiQuarkusCloudMetricsInfoResponses = {
  /**
   * Cloud static metrics retrieved successfully
   */
  200: OpenapiServiceComparasion
}

export type GetApiQuarkusCloudMetricsInfoResponse =
  GetApiQuarkusCloudMetricsInfoResponses[keyof GetApiQuarkusCloudMetricsInfoResponses]

export type GetApiQuarkusCloudMetricsLiveData = {
  body?: never
  path?: never
  query?: never
  url: "/api/quarkus/cloud/metrics/live"
}

export type GetApiQuarkusCloudMetricsLiveResponses = {
  /**
   * Cloud live metrics stream started
   */
  200: Array<OpenapiOutboundSseEvent>
}

export type GetApiQuarkusCloudMetricsLiveResponse =
  GetApiQuarkusCloudMetricsLiveResponses[keyof GetApiQuarkusCloudMetricsLiveResponses]

export type GetApiQuarkusHostnameData = {
  body?: never
  path?: never
  query?: never
  url: "/api/quarkus/hostname"
}

export type GetApiQuarkusHostnameResponses = {
  /**
   * OK
   */
  200: string
}

export type GetApiQuarkusHostnameResponse =
  GetApiQuarkusHostnameResponses[keyof GetApiQuarkusHostnameResponses]

export type GetApiQuarkusNoteData = {
  body?: never
  path?: never
  query?: never
  url: "/api/quarkus/note"
}

export type GetApiQuarkusNoteResponses = {
  /**
   * Notes retrieved successfully
   */
  200: OpenapiNotNullDataResponseListNotePublic
}

export type GetApiQuarkusNoteResponse =
  GetApiQuarkusNoteResponses[keyof GetApiQuarkusNoteResponses]

export type PostApiQuarkusNoteData = {
  body: OpenapiNoteCreate
  path?: never
  query?: never
  url: "/api/quarkus/note"
}

export type PostApiQuarkusNoteErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Validation error
   */
  422: OpenapiHttpValidationProblemPublic
}

export type PostApiQuarkusNoteError =
  PostApiQuarkusNoteErrors[keyof PostApiQuarkusNoteErrors]

export type PostApiQuarkusNoteResponses = {
  /**
   * Note created successfully
   */
  200: OpenapiNotNullDataResponseNotePublic
}

export type PostApiQuarkusNoteResponse =
  PostApiQuarkusNoteResponses[keyof PostApiQuarkusNoteResponses]

export type PutApiQuarkusNoteData = {
  body: OpenapiNoteUpdate
  path?: never
  query?: never
  url: "/api/quarkus/note"
}

export type PutApiQuarkusNoteErrors = {
  /**
   * Bad Request
   */
  400: unknown
  /**
   * Note not found
   */
  404: OpenapiHttpProblem
  /**
   * Validation error
   */
  422: OpenapiHttpValidationProblemPublic
}

export type PutApiQuarkusNoteError =
  PutApiQuarkusNoteErrors[keyof PutApiQuarkusNoteErrors]

export type PutApiQuarkusNoteResponses = {
  /**
   * Note updated successfully
   */
  200: OpenapiNotNullDataResponseNotePublic
}

export type PutApiQuarkusNoteResponse =
  PutApiQuarkusNoteResponses[keyof PutApiQuarkusNoteResponses]

export type DeleteApiQuarkusNoteByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/quarkus/note/{id}"
}

export type DeleteApiQuarkusNoteByIdErrors = {
  /**
   * Note not found
   */
  404: OpenapiHttpProblem
  /**
   * Validation error
   */
  422: OpenapiHttpValidationProblem
  /**
   * Internal Server Error
   */
  500: OpenapiHttpProblem
}

export type DeleteApiQuarkusNoteByIdError =
  DeleteApiQuarkusNoteByIdErrors[keyof DeleteApiQuarkusNoteByIdErrors]

export type DeleteApiQuarkusNoteByIdResponses = {
  /**
   * Note deleted successfully
   */
  200: OpenapiSimpleResponse
}

export type DeleteApiQuarkusNoteByIdResponse =
  DeleteApiQuarkusNoteByIdResponses[keyof DeleteApiQuarkusNoteByIdResponses]

export type OpenapiGetAllData = {
  body?: never
  path?: never
  query?: never
  url: "/api/spring/note"
}

export type OpenapiGetAllResponses = {
  /**
   * Notes retrieved successfully
   */
  200: OpenapiNotNullDataResponseListNotePublic
}

export type OpenapiGetAllResponse =
  OpenapiGetAllResponses[keyof OpenapiGetAllResponses]

export type OpenapiCreateData = {
  body: OpenapiNoteCreate
  path?: never
  query?: never
  url: "/api/spring/note"
}

export type OpenapiCreateErrors = {
  /**
   * Invalid input data
   */
  400: OpenapiNotNullDataResponseNotePublic
}

export type OpenapiCreateError = OpenapiCreateErrors[keyof OpenapiCreateErrors]

export type OpenapiCreateResponses = {
  /**
   * Note created successfully
   */
  200: OpenapiNotNullDataResponseNotePublic
}

export type OpenapiCreateResponse =
  OpenapiCreateResponses[keyof OpenapiCreateResponses]

export type OpenapiUpdateData = {
  body: OpenapiNoteUpdate
  path?: never
  query?: never
  url: "/api/spring/note"
}

export type OpenapiUpdateErrors = {
  /**
   * Invalid input data
   */
  400: OpenapiProblemDetailPublic
  /**
   * Note not found
   */
  404: OpenapiProblemDetailPublic
}

export type OpenapiUpdateError = OpenapiUpdateErrors[keyof OpenapiUpdateErrors]

export type OpenapiUpdateResponses = {
  /**
   * Note updated successfully
   */
  200: OpenapiNotNullDataResponseNotePublic
}

export type OpenapiUpdateResponse =
  OpenapiUpdateResponses[keyof OpenapiUpdateResponses]

export type OpenapiHostnameData = {
  body?: never
  path?: never
  query?: never
  url: "/api/spring/hostname"
}

export type OpenapiHostnameResponses = {
  /**
   * OK
   */
  200: string
}

export type OpenapiHostnameResponse =
  OpenapiHostnameResponses[keyof OpenapiHostnameResponses]

export type OpenapiLiveMetricsStreamData = {
  body?: never
  path?: never
  query?: never
  url: "/api/spring/cloud/metrics/live"
}

export type OpenapiLiveMetricsStreamResponses = {
  /**
   * Cloud live metrics stream started
   */
  200: OpenapiSseEmitter
}

export type OpenapiLiveMetricsStreamResponse =
  OpenapiLiveMetricsStreamResponses[keyof OpenapiLiveMetricsStreamResponses]

export type OpenapiStaticMetricsData = {
  body?: never
  path?: never
  query?: never
  url: "/api/spring/cloud/metrics/info"
}

export type OpenapiStaticMetricsResponses = {
  /**
   * Cloud static metrics retrieved successfully
   */
  200: OpenapiServiceComparasion
}

export type OpenapiStaticMetricsResponse =
  OpenapiStaticMetricsResponses[keyof OpenapiStaticMetricsResponses]

export type OpenapiDeleteData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/spring/note/{id}"
}

export type OpenapiDeleteErrors = {
  /**
   * Invalid note ID format
   */
  400: OpenapiProblemDetail
  /**
   * Note not found
   */
  404: OpenapiProblemDetail
  /**
   * Internal Server Error
   */
  500: OpenapiProblemDetail
}

export type OpenapiDeleteError = OpenapiDeleteErrors[keyof OpenapiDeleteErrors]

export type OpenapiDeleteResponses = {
  /**
   * Note deleted successfully
   */
  200: OpenapiSimpleResponse
}

export type OpenapiDeleteResponse =
  OpenapiDeleteResponses[keyof OpenapiDeleteResponses]
