// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

export const zOpenapiErrorMessage = z.object({
  code: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  message: z.string(),
  details: z.string().optional(),
})

export const zOpenapiErrorMessagePublic = z.object({
  code: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  message: z.string(),
  details: z.string().optional(),
})

export const zOpenapiNoteCreate = z.object({
  content: z.string().min(1),
})

export const zOpenapiNotePublic = z.object({
  id: z.string(),
  content: z.string().min(1),
})

export const zOpenapiNotNullDataResponseListNotePublic = z.object({
  data: z.array(zOpenapiNotePublic),
  detail: z.string(),
})

export const zOpenapiNotNullDataResponseNotePublic = z.object({
  data: zOpenapiNotePublic,
  detail: z.string(),
})

export const zOpenapiNoteUpdate = z.object({
  id: z.string(),
  content: z.string().min(1),
})

export const zOpenapiSimpleResponse = z.object({
  detail: z.string(),
})

export const zOpenapiValidationErrorMessage = z.object({
  errors: z.array(z.string()),
})

export const zOpenapiValidationErrorMessagePublic = z.object({
  errors: z.array(z.string()),
})

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpProblem = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  detail: z.string().optional(),
  instance: z.url(),
})

/**
 * Validation constraint violation details
 */
export const zOpenapiViolation = z.object({
  field: z.string(),
  in: z.string(),
  message: z.string(),
})

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpValidationProblem = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  detail: z.string().optional(),
  instance: z.url(),
  violations: z.array(zOpenapiViolation).optional(),
})

/**
 * Validation constraint violation details
 */
export const zOpenapiViolationPublic = z.object({
  field: z.string().optional(),
  in: z.string().optional(),
  message: z.string().optional(),
})

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpValidationProblemPublic = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  detail: z.string().optional(),
  instance: z.url().optional(),
  violations: z.array(zOpenapiViolationPublic).optional(),
})

export const zOpenapiProblemDetailPublic = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  detail: z.string().optional(),
  instance: z.url().optional(),
  properties: z.record(z.string(), z.unknown()).optional(),
})

export const zOpenapiProblemDetail = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  detail: z.string().optional(),
  instance: z.url().optional(),
  properties: z.record(z.string(), z.unknown()).optional(),
})

/**
 * OK
 */
export const zGetApiDropwizardHostnameResponse = z.string()

/**
 * Notes retrieved successfully
 */
export const zGetApiDropwizardNoteResponse =
  zOpenapiNotNullDataResponseListNotePublic

export const zPostApiDropwizardNoteBody = zOpenapiNoteCreate

/**
 * Note created successfully
 */
export const zPostApiDropwizardNoteResponse =
  zOpenapiNotNullDataResponseNotePublic

export const zPutApiDropwizardNoteBody = zOpenapiNoteUpdate

/**
 * Note updated successfully
 */
export const zPutApiDropwizardNoteResponse =
  zOpenapiNotNullDataResponseNotePublic

export const zDeleteApiDropwizardNoteByIdPath = z.object({
  id: z.string().regex(/^[a-fA-F0-9]{24}$/),
})

/**
 * Note deleted successfully
 */
export const zDeleteApiDropwizardNoteByIdResponse = zOpenapiSimpleResponse

/**
 * OK
 */
export const zGetApiQuarkusHostnameResponse = z.string()

/**
 * Notes retrieved successfully
 */
export const zGetApiQuarkusNoteResponse =
  zOpenapiNotNullDataResponseListNotePublic

export const zPostApiQuarkusNoteBody = zOpenapiNoteCreate

/**
 * Note created successfully
 */
export const zPostApiQuarkusNoteResponse = zOpenapiNotNullDataResponseNotePublic

export const zPutApiQuarkusNoteBody = zOpenapiNoteUpdate

/**
 * Note updated successfully
 */
export const zPutApiQuarkusNoteResponse = zOpenapiNotNullDataResponseNotePublic

export const zDeleteApiQuarkusNoteByIdPath = z.object({
  id: z.string(),
})

/**
 * Note deleted successfully
 */
export const zDeleteApiQuarkusNoteByIdResponse = zOpenapiSimpleResponse

/**
 * Notes retrieved successfully
 */
export const zOpenapiGetAllResponse = zOpenapiNotNullDataResponseListNotePublic

export const zOpenapiCreateBody = zOpenapiNoteCreate

/**
 * Note created successfully
 */
export const zOpenapiCreateResponse = zOpenapiNotNullDataResponseNotePublic

export const zOpenapiUpdateBody = zOpenapiNoteUpdate

/**
 * Note updated successfully
 */
export const zOpenapiUpdateResponse = zOpenapiNotNullDataResponseNotePublic

/**
 * OK
 */
export const zOpenapiHostnameResponse = z.string()

export const zOpenapiDeletePath = z.object({
  id: z.string(),
})

/**
 * Note deleted successfully
 */
export const zOpenapiDeleteResponse = zOpenapiSimpleResponse
