// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

export const zOpenapiErrorMessage = z.object({
  code: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  message: z.string(),
  details: z.string().optional(),
})

export const zOpenapiErrorMessagePublic = z.object({
  code: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  message: z.string(),
  details: z.string().optional(),
})

export const zOpenapiImagePlatformDigest = z.object({
  architecture: z.string().optional(),
  digest: z.string().optional(),
  size: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
})

export const zOpenapiImageManifestSummary = z.object({
  image: z.string().optional(),
  imageReference: z.string().optional(),
  platforms: z.array(zOpenapiImagePlatformDigest).optional(),
})

export const zOpenapiNoteCreate = z.object({
  content: z.string().min(1),
})

export const zOpenapiNotePublic = z.object({
  id: z.string(),
  content: z.string().min(1),
})

export const zOpenapiNotNullDataResponseListNotePublic = z.object({
  data: z.array(zOpenapiNotePublic),
  detail: z.string(),
})

export const zOpenapiNotNullDataResponseNotePublic = z.object({
  data: zOpenapiNotePublic,
  detail: z.string(),
})

export const zOpenapiNoteUpdate = z.object({
  id: z.string(),
  content: z.string().min(1),
})

export const zOpenapiServiceComparasion = z.object({
  framework: z.string().optional(),
  service: z.string().optional(),
  runtimeMode: z.string().optional(),
  version: z.string().optional(),
  hostname: z.string().optional(),
  startupReadyMs: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  images: z.array(zOpenapiImageManifestSummary).optional(),
})

export const zOpenapiServiceResourceSnapshot = z.object({
  availableProcessors: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  maxMemoryBytes: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalMemoryBytes: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  freeMemoryBytes: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  usedMemoryBytes: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  usedMemoryMiB: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  javaVersion: z.string().optional(),
  vmName: z.string().optional(),
  osName: z.string().optional(),
  osArch: z.string().optional(),
})

export const zOpenapiServiceStartupMetrics = z.object({
  processStartedAt: z.iso.datetime().optional(),
  processUptimeMs: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  processUptimeSeconds: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
})

export const zOpenapiServiceLiveMetrics = z.object({
  collectedAt: z.iso.datetime().optional(),
  startupMetrics: zOpenapiServiceStartupMetrics.optional(),
  resourceSnapshot: zOpenapiServiceResourceSnapshot.optional(),
})

export const zOpenapiSimpleResponse = z.object({
  detail: z.string(),
})

export const zOpenapiValidationErrorMessage = z.object({
  errors: z.array(z.string()),
})

export const zOpenapiValidationErrorMessagePublic = z.object({
  errors: z.array(z.string()),
})

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpProblem = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  detail: z.string().optional(),
  instance: z.url(),
})

export const zOpenapiMediaType = z.object({
  type: z.string().optional(),
  subtype: z.string().optional(),
  parameters: z.record(z.string(), z.string()).optional(),
  hash: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  wildcardType: z.boolean().optional(),
  wildcardSubtype: z.boolean().optional(),
})

export const zOpenapiOutboundSseEvent = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  comment: z.string().optional(),
  reconnectDelay: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  reconnectDelaySet: z.boolean().optional(),
  type: z.record(z.string(), z.unknown()).optional(),
  genericType: z.record(z.string(), z.unknown()).optional(),
  mediaType: zOpenapiMediaType.optional(),
  data: z.unknown().optional(),
})

/**
 * Validation constraint violation details
 */
export const zOpenapiViolation = z.object({
  field: z.string(),
  in: z.string(),
  message: z.string(),
})

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpValidationProblem = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  detail: z.string().optional(),
  instance: z.url(),
  violations: z.array(zOpenapiViolation).optional(),
})

/**
 * Validation constraint violation details
 */
export const zOpenapiViolationPublic = z.object({
  field: z.string().optional(),
  in: z.string().optional(),
  message: z.string().optional(),
})

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpValidationProblemPublic = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  detail: z.string().optional(),
  instance: z.url().optional(),
  violations: z.array(zOpenapiViolationPublic).optional(),
})

export const zOpenapiProblemDetailPublic = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  detail: z.string().optional(),
  instance: z.url().optional(),
  properties: z.record(z.string(), z.unknown()).optional(),
})

export const zOpenapiSseEmitter = z.object({
  timeout: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
})

export const zOpenapiProblemDetail = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  detail: z.string().optional(),
  instance: z.url().optional(),
  properties: z.record(z.string(), z.unknown()).optional(),
})

/**
 * Cloud static metrics retrieved successfully
 */
export const zGetApiDropwizardCloudMetricsInfoResponse =
  zOpenapiServiceComparasion

/**
 * Cloud live metrics stream started
 */
export const zGetApiDropwizardCloudMetricsLiveResponse =
  zOpenapiServiceLiveMetrics

/**
 * OK
 */
export const zGetApiDropwizardHostnameResponse = z.string()

/**
 * Notes retrieved successfully
 */
export const zGetApiDropwizardNoteResponse =
  zOpenapiNotNullDataResponseListNotePublic

export const zPostApiDropwizardNoteBody = zOpenapiNoteCreate

/**
 * Note created successfully
 */
export const zPostApiDropwizardNoteResponse =
  zOpenapiNotNullDataResponseNotePublic

export const zPutApiDropwizardNoteBody = zOpenapiNoteUpdate

/**
 * Note updated successfully
 */
export const zPutApiDropwizardNoteResponse =
  zOpenapiNotNullDataResponseNotePublic

export const zDeleteApiDropwizardNoteByIdPath = z.object({
  id: z.string().regex(/^[a-fA-F0-9]{24}$/),
})

/**
 * Note deleted successfully
 */
export const zDeleteApiDropwizardNoteByIdResponse = zOpenapiSimpleResponse

/**
 * Cloud static metrics retrieved successfully
 */
export const zGetApiQuarkusCloudMetricsInfoResponse = zOpenapiServiceComparasion

/**
 * Cloud live metrics stream started
 */
export const zGetApiQuarkusCloudMetricsLiveResponse = z.array(
  zOpenapiOutboundSseEvent
)

/**
 * OK
 */
export const zGetApiQuarkusHostnameResponse = z.string()

/**
 * Notes retrieved successfully
 */
export const zGetApiQuarkusNoteResponse =
  zOpenapiNotNullDataResponseListNotePublic

export const zPostApiQuarkusNoteBody = zOpenapiNoteCreate

/**
 * Note created successfully
 */
export const zPostApiQuarkusNoteResponse = zOpenapiNotNullDataResponseNotePublic

export const zPutApiQuarkusNoteBody = zOpenapiNoteUpdate

/**
 * Note updated successfully
 */
export const zPutApiQuarkusNoteResponse = zOpenapiNotNullDataResponseNotePublic

export const zDeleteApiQuarkusNoteByIdPath = z.object({
  id: z.string(),
})

/**
 * Note deleted successfully
 */
export const zDeleteApiQuarkusNoteByIdResponse = zOpenapiSimpleResponse

/**
 * Notes retrieved successfully
 */
export const zOpenapiGetAllResponse = zOpenapiNotNullDataResponseListNotePublic

export const zOpenapiCreateBody = zOpenapiNoteCreate

/**
 * Note created successfully
 */
export const zOpenapiCreateResponse = zOpenapiNotNullDataResponseNotePublic

export const zOpenapiUpdateBody = zOpenapiNoteUpdate

/**
 * Note updated successfully
 */
export const zOpenapiUpdateResponse = zOpenapiNotNullDataResponseNotePublic

/**
 * OK
 */
export const zOpenapiHostnameResponse = z.string()

/**
 * Cloud live metrics stream started
 */
export const zOpenapiLiveMetricsStreamResponse = zOpenapiSseEmitter

/**
 * Cloud static metrics retrieved successfully
 */
export const zOpenapiStaticMetricsResponse = zOpenapiServiceComparasion

export const zOpenapiDeletePath = z.object({
  id: z.string(),
})

/**
 * Note deleted successfully
 */
export const zOpenapiDeleteResponse = zOpenapiSimpleResponse
